name: Jest

on: [push]

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - run: npm install

      - run: npm run test
